/*
CREATE TABLE turmas (
 	id SERIAL PRIMARY KEY,
	nome VARCHAR(15) NOT NULL

);

CREATE TABLE alunos (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE,
	id_turma INT NOT NULL,
	FOREIGN KEY (id_turma)
	REFERENCES turmas(id)
);
*/

CREATE TABLE professor (
	id SERIAL PRIMARY KEY,
	nome VARCHAR (50) NOT NULL,
	email VARCHAR (50) UNIQUE NOT NULL,
	especialidade VARCHAR (50) NOT NULL
);

CREATE TABLE disciplina (
	id SERIAL PRIMARY KEY,
	nome VARCHAR (50) NOT NULL,
	carga_horaria INT NOT NULL
);

CREATE TABLE curso (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	descricao VARCHAR(50) NOT NULL
);




